name: serpapi4j CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
	matrix:
      java: [ '14', '15', '16' ]
    name: Build on java version ${{ matrix.java }}
      steps:
      - name: Checking out this git repo
        uses: actions/checkout@v3
      - name: Setup Java JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.4.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      cache: 'maven'
      - name: Build with Maven for ${{ matrix.java }}
        env:
	      SERPAPI_KEY: ${{ secrets.SERPAPI_SECRET_KEY }}
        run: mvn --batch-mode --update-snapshots verify